#!/bin/bash

# Define core parameters - rawdata, pipedir, moduledir, assembly_name
# sourcedir="/path/to/rawreads/"
pipedir=$(pwd -P)

moduledir="${pipedir}/modules"
scriptdir="${moduledir}/scripts"
sourcedir="${pipedir}/source_data"

## Make workdir and output directories
outdir="${pipedir}/outdir"
log="${workdir}/0_log"
singularitydir="${pipedir}/singularities"

# Create Singularity cache directory in /tmp and set environment variables
if [[ ! -d "${singularitydir}" ]]; then
        mkdir -p "${singularitydir}"
fi

if [[ ! -d "${singularitydira}/cache" ]]; then
        mkdir -p "${singularitydir}/cache"
fi

export APTAINERAPTAINER_CACHEDIR=${singularitydir}/cache
export APPTAINER_CACHEDIR=${singularitydir}/cache

#create output directories if not present

if [[ ! -d ${workdir} ]]; then 
	mkdir -p ${workdir}
fi

if [[ ! -d "${outdir}" ]]; then 
	mkdir -p "${outdir}" 
fi

if [[ ! -d "${log}" ]]; then
        mkdir -p "${log}"
fi

# Export core parameters
export sourcedir
export pipedir
export workdir
export outdir
export moduledir
export log
export singularitydir
export scriptdir

# Step 1: Rename and Count
rawdir="${workdir}/1_raw_data"
if [[ ! -d "${rawdir}" ]]; then 
	mkdir -p "${rawdir}" 
fi
export rawdir

#STEP 2A: fastqc on raw data
qcdir="${workdir}/2A_rawqc" 
if [[ ! -d "${qcdir}" ]]; then 
	mkdir -p "${qcdir}" 
fi
export qcdir

#2B fastp trim
trimdir="${workdir}/2B_trim_files"
if [[ ! -d "${trimdir}" ]]; then
        mkdir -p "${trimdir}"
fi
export trimdir

#STEP 2C: qc trim reads
trimqc="${workdir}/2C_trimqc"
if [[ ! -d "${trimqc}" ]]; then
        mkdir -p "${trimqc}"
fi
export trimqc


#STEP 2D: remove adapters
cutdir="${workdir}/2E_cutdir"
if [[ ! -d "${cutdir}" ]]; then
        mkdir -p "${cutdir}"
fi
export cutdir

#STEP 3A: QIIME INPUT and QC
q2_input="${workdir}/3A_q2_input"
if [[ ! -d "${q2_input}" ]]; then
        mkdir -p "${q2_input}"
fi

q2_dada2="${workdir}/3B_q2_dada2"
if [[ ! -d "${q2_dada2}" ]]; then
        mkdir -p "${q2_dada2}"
fi

q2_summary="${workdir}/3C_q2_summary"
if [[ ! -d "${q2_summary}" ]]; then
        mkdir -p "${q2_summary}"
fi

export q2_input
export q2_dada2
export q2_summary

#STEP 4: QIIME2 TAX
q2_tax="${workdir}/4A_q2_tax"
if [[ ! -d "${q2_tax}" ]]; then
        mkdir -p "${q2_tax}"
fi

export q2_tax

#STEP 5: QIIME2 Metrics
q2_metric="${workdir}/5_q2_metric"
if [[ ! -d "${q2_metric}" ]]; then
        mkdir -p "${q2_metric}"
fi

export q2_metric

#STEP 6: QIIME2 Export
q2_extracted="${workdir}/6_q2_export"
if [[ ! -d "${q2_extracted}" ]]; then
        mkdir -p "${q2_extracted}"
fi

export q2_extracted

# STEP X:
multiqcdir="${workdir}/multiqc"
if [[ ! -d "${multiqcdir}" ]]; then
        mkdir -p "${multiqcdir}"
fi

export multiqcdir


