#!/bin/bash

#STEP2A-2C
fastqc_module="FastQC/0.12.1-Java-11"
module is-avail ${fastqc_module} || { echo "${fastqc_module} not avalible check config.parameters_all file" ; exit 1; }
export fastqc_module

#2B fastp trim
fastp_module="fastp/1.3.3-GCC-15.2.0"
module is-avail ${fastp_module} || { echo "${fastp_module} not avalible check config.parameters_all file" ; exit 1; }
export fastp_module

#2E rc_primer
seqtk_module="seqtk/1.5-GCC-14.2.0"
module is-avail ${seqtk_module} || { echo "${seqtk_module} not avalible check config.parameters_all file" ; exit 1; }
export seqtk_module


#2E cutadapt
cutadapt_module="cutadapt/5.2-GCCcore-14.3.0"
module is-avail ${cutadapt_module} || { echo "${cutadapt_module} not avalible check config.parameters_all file" ; exit 1; }
export cutadapt_module



#STEPS 4-6: QIIME 
q2_module="QIIME2/2026.4-rachis-conda"
module is-avail ${q2_module} || { echo "${q2_module} not avalible check config.parameters_all file" ; exit 1; }
export q2_module


#STEP X:
multiqc_module="MultiQC/1.28-gfbf-2024a"
module is-avail ${multiqc_module} || { echo "${multiqc_module} not avalible check config.parameters_all file" ; exit 1; }
export multiqc_module
